[package]
name = "terrustrial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug = true
lto = "fat"
incremental = true


[features]
default = ["simba", "simba/wide"]
packed = ["simba", "simba/packed_simd"]

[dependencies]
approx = "0.5.1"
faer = "0.17.1"
faer-core = "0.17.1"
faer-cholesky = "0.17.1"
nalgebra = { version = "0.32.3", features = ["std"] }
ndarray = "0.15.6"
num-traits = "0.2.15"
parry3d = { version = "0.13.5", features = ["simd-stable"] }
rand = "0.8.5"
rstar = { version = "0.11.0", features = ["serde"] }
dyn-stack = "0.10.0"
# simba = { git = "https://github.com/dimforge/simba.git", branch = "master", features = [
#     "packed_simd",
# ] }
serde = { version = "1", features = ["derive"] }

simba = { version = "0.8.1", optional = true }
bitvec = "1.0.1"
ordered-float = "3.7.0"
indicatif = { version = "0.17.5", features = ["rayon"] }
rayon = "1.7.0"
csv = "1.2.2"
itertools = "0.11.0"
rand_distr = "0.4.3"
mathru = "0.15.2"
parking_lot = "0.12.1"
# cudarc = "0.9.15"
bytemuck = { version = "1.14.0", features = ["derive"] }
bvh = { git = "https://github.com/svenstaro/bvh.git" }
rmpfit = "0.3.0"
argmin = { version = "0.8" }
argmin-math = { version = "0.3", features = [
    "ndarray_latest-serde",
    "nalgebra_latest-serde",
] }
#Fails to build with rust 1.73 due to packed_simd_2 dependency
#simply updates dependency to packed_simd 0.3.9
#subscribed to merge request on github, remove when merged
[patch.crates-io]
simba = { git = "https://github.com/dimforge/simba.git", branch = "master" }
