[package]
name = "terrustrial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug = true
lto = "fat"

[dependencies]
approx = "0.5.1"
faer = "0.7.0"
faer-core = "0.9.1"
faer-cholesky = "0.9.1"
nalgebra = "0.32.2"
ndarray = "0.15.6"
num-traits = "0.2.15"
parry3d = { version = "0.13.4", features = ["simd-stable"] }
rand = "0.8.5"
rstar = "0.11.0"
dyn-stack = "0.9.0"
simba = { version = "0.8.1", features = ["packed_simd"] }
bitvec = "1.0.1"
ordered-float = "3.7.0"
indicatif = {version = "0.17.5", features = ["rayon"]}
rayon = "1.7.0"
csv = "1.2.2"
itertools = "0.11.0"
